version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
  backend:
    build: 
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - database